server:
  port: 8080
  
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://47.105.96.18:3306/zysy
    url: jdbc:mysql://localhost/zysy
    username: root
    #password: ad310e80d6f3ef1848f49e71.
    password: mysql
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
